### PR TITLE
Add documentation for creating a homepage with `VitePress`

### PR DESCRIPTION
**Pull request by WillHannon-MCB**
[`VitePress`](https://vitepress.dev/) offers a nice way to organize the pipeline's results in a stylized static site. This pull request includes documentation and example code for adding a `VitePress` site to new and existing `dms-vep-pipeline` projects.

### CODE REVIEW

**Comment by jbloom** [comment]
@WillHannon-MCB, do you know how to fix the error in the tests here? It seems to have to do with building the `conda` env:
https://github.com/dms-vep/dms-vep-pipeline-3/actions/runs/8792655133/job/24129218860?pr=116

**Comment by WillHannon-MCB** [comment]
@jbloom, that's odd. I didn't change the `environment.yml` file at all. It doesn't appear in the list of changed files. I'll see what's happening. When was the last time you ran these tests?

**Comment by jbloom** [comment]
Last time I ran it was whenever last pull request was merged. Maybe something strange happened with `conda`. It looks like `mafft` is what is throwing the error, and there is a new version of `mafft` out. So worst case, you could update the `mafft` version in the `environment.yml` and see if that fixes it.

**Comment by jbloom** [comment]
@WillHannon-MCB, can you also update CHANGELOG for this new version to indicate you upgraded `mafft` in the environment?

**Comment by WillHannon-MCB** [comment]
I'll update the CHANGELOG. Are you familiar with the issue the linter has with the new rule?

```
Run cd test_example && snakemake -s ../Snakefile --lint && cd ..
/home/runner/work/dms-vep-pipeline-3/dms-vep-pipeline-3/test_example/../Snakefile:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  )
Lints for rule build_vitepress_homepage (line 144, /home/runner/work/dms-vep-pipeline-3/dms-vep-pipeline-3/docs.smk):
    * Param docs is a prefix of input or output file but hardcoded:
      If this is meant to represent a file path prefix, it will fail when
      running workflow in environments without a shared filesystem. Instead,
      provide a function that infers the appropriate prefix from the input or
      output file, e.g.: lambda w, input: os.path.splitext(input[0])[0]
      Also see:
      https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#non-file-parameters-for-rules
      https://snakemake.readthedocs.io/en/stable/tutorial/advanced.html#tutorial-input-functions
    * Param homepage is a prefix of input or output file but hardcoded:
      If this is meant to represent a file path prefix, it will fail when
      running workflow in environments without a shared filesystem. Instead,
      provide a function that infers the appropriate prefix from the input or
      output file, e.g.: lambda w, input: os.path.splitext(input[0])[0]
      Also see:
      https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#non-file-parameters-for-rules
      https://snakemake.readthedocs.io/en/stable/tutorial/advanced.html#tutorial-input-functions
      ```

**Comment by jbloom** [comment]
The idea is that if you are just using params to get the prefix of a file that is input, you should do that using the name defined as input rather than separately coding it in params. Otherwise you are effectively writing the same thing in two different places.

The params can be lambda functions that take input as a named variable, so make it:
```
input:
    file=<full file path>
params:
   subdir=lambda _, input: os.path.dirname(input.file)
```

Right now you are instead separately hardcoding `subdir` to be the subdirectory for `input.file`.

Does that make sense?

**Comment by WillHannon-MCB** [comment]
Ah, okay. That makes sense.

**Review by jbloom — APPROVED** [review]

**Pull request merged**
