### PR TITLE
move model instantiation inside loop

### PR DESCRIPTION
**Pull request by jgallowa07**
This addresses #92

### CODE REVIEW

**Comment by jgallowa07** [comment]
Seems that the tests are failing due to
```
Run nbqa ruff .
/usr/share/miniconda/envs/dms-vep-pipeline-3/bin/python3.11: No module named ruff
Error: Process completed with exit code 1.
```
Not exactly sure why this is happening (I only changed a single line of code).  Looking into it now

**Comment by jbloom** [comment]
I am going to look at your pulls soon (was behind)---but yes, the failures were because `ruff` is now supposed to run directly on notebooks rather than via `nbqa` as was done prior to the pull request I just made.

**Comment by jgallowa07** [comment]
Great, seems to be working now.  Thanks to @Caleb-Carr for getting me to do this - and apologies for not making this patch a priority over the rest of #86. I realize this is non-trivial so it's worth mentioning to others who are looking at these results. The main problem this bug introduces is that the chosen [lasso_shift](https://github.com/dms-vep/dms-vep-pipeline-3/blob/8b7ad8e97e79b242326c6e7a50d9b8f6211527e9/test_example/data/func_effects_config.yml#L245) average model would essentially represent the training of all [lasso_shifts](https://github.com/dms-vep/dms-vep-pipeline-3/blob/8b7ad8e97e79b242326c6e7a50d9b8f6211527e9/test_example/data/func_effects_config.yml#L169) preceding it.

> I am going to look at your pulls soon (was behind) -- 

No rush on my end, I'm in a similar boat - #91 is still a WIP so nothing to look at currently - later this week hopefully.

**Review by jbloom — APPROVED** [review]
Makes sense. I'm not sure if the prior behavior was a bug strictly speaking (that is also a way to do it, right?) but I'm fine with this change.

**Pull request merged**
